[package]
name = "grepr"
version = "0.1.0"
authors = ["Bruno Flores"]
edition = "2019"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
